---
- name: Setup DBserver
  hosts: databasegrp
  become: yes
#Defining variables into the playbook
  vars:
    dbname: website
    dbuser: devops
    dbpass: 12345
  tasks:
#Definfing the debug to print the msg 
    - debug:
      var: dbname
    - debug:
      msg: "Value of the dbuser is {{dbuser}}"     
    
    - name: Install mariadb server
      yum:
        name: mariadb-server
        state: present

    - name: Install Python MySQL
      yum:
         name: MySQL-python
         state: present

    - name: Start & Enable mariadb-server
      service:
           name: mariadb
           state: started
           enabled: yes

    - name: Create a new database with name 'website'
      mysql_db:
         name: "{{dbname}}"
         state: present

    - name: Create database user with name 'web' with all database privileges
      mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
